### PR TITLE
feat: use official docker rust image

### LINKED ISSUE #2: Not using the official docker image
Is there a reason why this example doesn't use the [official rust docker image](https://hub.docker.com/_/rust/)?
I ran into issues with the `Dockerfile` in this example because `liuchong/rustup:stable` is not up to date and was getting a

```
error: failed to parse manifest at `Cargo.toml`

Caused by:
  feature `edition2021` is required
```

My cargo file had something like 
```
[package]
edition = "2021"

```
And I had to change it to `edition = "2018"`, to work with the `Dockerfile` in this example, even though the latest stable rust release supports [edition 2021](https://github.com/rust-lang/rust/blob/master/RELEASES.md#language-4).

I can look into opening a PR for this if this is something that could be helpful for others.

### PR DESCRIPTION
**Pull request by brleinad**
- Also changed to the latest stable debian image

resolve #2

### CODE REVIEW

**Comment by brleinad** [comment]
@jeromegn I tested the deploy: https://hello-rust-brleinad.fly.dev/ 

I decided to update to the latest stable slim debian image, as per the example [here](https://hub.docker.com/_/rust/?tab=description), and had to make a change in the `COPY` command because of this.

**Comment by jeromegn** [comment]
I've been playing with this for one of our Rust projects and it seems about right!

Best way to cache the cargo builds would be to use a "RUN mount" like this:

```dockerfile
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/src/app/target \
    cargo build --release
```

The Docker daemon does need buildkit enabled. This is true for the Fly remote builders.

**Comment by brleinad** [comment]
Thanks! I made the change, is that what you had in mind?

**Comment by jeromegn** [comment]
Yes, that looks right. I assume you tested that it works? :)

**Comment by brleinad** [comment]
I did! Still running here https://hello-rust-brleinad.fly.dev/

Btw, the more I use fly.io the more I like. I will definitely be using it more in the future.

**Comment by jeromegn** [comment]
Thank you! This is a good improvement!

**Pull request merged**
